---
- name: Masinate kontroll
  hosts: Linux
  gather_facts: yes
  become: yes

  vars:
    req_pack:
      - git
      - tree
      - wget
      - mc
      - tmux
      - snmpd

  tasks:
  - name: Mis on masinasse installitud
    ansible.builtin.package_facts:
      manager: auto

  - name: Mida pole installeeritud
    debug:
      msg: "Puudu: {{ req_pack | difference(ansible_facts.packages.keys() | list) }}"
    when: ansible_distribution not in ['openSUSE Leap', 'openSUSE'] and ((req_pack | difference(ansible_facts.packages.keys() | list)) | length > 0)
  - name: Install missing packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: "{{ req_pack | difference(ansible_facts.packages.keys() | list) }}"
    when: ansible_distribution not in ['openSUSE Leap', 'openSUSE']
    
...